name: Docker镜像打包为离线包

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写 Docker 镜像名称 (多个用英文逗号分开)'
        required: true
        default: 'alpine:latest'
      custom_name:
        description: '可选: 自定义发布名称'
        required: false
      tag:
        description: '可选: 发布标签 (默认为当前日期)'
        required: false

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull and Save Docker Images
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          image_name="${image%%:*}"
          image_name="${image_name##*/}"
          file_name="${image_name}.tar"
          docker pull "${image}"
          docker save "${image}" -o "${file_name}"
        done

    - name: List Files for Debugging
      run: ls -lh

    - name: Set File Name
      id: set_file_name
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        num_images=${#image_array[@]}

        if [ $num_images -eq 1 ]; then
          original_file="${image_array[0]%%:*}.tar"
          if [ -z "${{ github.event.inputs.custom_name }}" ]; then
            custom_file="$original_file"
          else
            custom_file="${{ github.event.inputs.custom_name }}.tar"
          fi
        else
          custom_file="$(date +'%Y%m%d').tar.gz"
          if [ -n "${{ github.event.inputs.custom_name }}" ]; then
            custom_file="${{ github.event.inputs.custom_name }}.tar.gz"
          fi
        fi
        echo "custom_file=$custom_file" >> $GITHUB_ENV

    - name: Compress if necessary
      if: ${{ steps.set_file_name.outputs.custom_file }} == *.tar.gz
      run: tar -czf "${{ env.custom_file }}" *.tar

    - name: Rename file if needed
      run: |
        if [ -f "${{ env.custom_file }}" ]; then
          echo "文件已存在: ${{ env.custom_file }}"
        else
          mv "$(ls *.tar)" "${{ env.custom_file }}"
        fi
        ls -lh

    - name: Check file size
      run: |
        file="${{ env.custom_file }}"
        file_size=$(stat -c%s "$file")
        max_size=$((2 * 1024 * 1024 * 1024))
        if [ "$file_size" -gt "$max_size" ]; then
          echo "EXCEEDS_LIMIT=true" >> $GITHUB_ENV
        else
          echo "EXCEEDS_LIMIT=false" >> $GITHUB_ENV
        fi

    - name: Get release name and tag
      run: |
        tag_name="${{ github.event.inputs.tag }}"
        if [ -z "$tag_name" ]; then
          tag_name=$(date +'%Y%m%d')
        fi
        echo "RELEASE_TAG=$tag_name" >> $GITHUB_ENV

    - name: Upload to GitHub Release (if under 2GB)
      if: env.EXCEEDS_LIMIT == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        files: ${{ env.custom_file }}
        body: "Daily Docker Images for ${{ env.RELEASE_TAG }}"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload as artifact (if over 2GB)
      if: env.EXCEEDS_LIMIT == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.custom_file }}
        path: ${{ env.custom_file }}

    - name: Clean up intermediate files
      run: rm *.tar*
